# Generated by Django 3.1.4 on 2022-10-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(default='', max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('comment', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
